### ISSUE TITLE
It's Modern, but not Fluent

### ISSUE THREAD

**Issue by UlyssesWu** [ms-design/ms-design#34]
首先感谢作者创造了一个很棒的项目。这个Issue并非是指责，只是想探讨下作者和我是否对Fluent Design Language有什么误解。

就展示页面上所见，此项目的效果看上去并没有多少**FDL**的元素在里面（最基本的Acrylic和Reveal都无，只有图标是符合FDL的），只是单纯的Win10 Modern风格（也叫**MDL**）。效果类似的项目[Winstrap](http://winstrap.azurewebsites.net/index.html)也说自己是MDL，而不是FDL。

不过这个项目的名字ms-design起的好，完全可以说是实现了MDL风格，而不用说是FDL。

[react-uwp](https://www.react-uwp.com/)则是真正的FDL，虽然它的Reveal并非真正的Reveal，但至少有那么个意思。

**Comment by ApsarasX** [comment]
> 首先感谢作者创造了一个很棒的项目。这个Issue并非是指责，只是想探讨下作者和我是否对Fluent Design Language有什么误解。
> 
> 就展示页面上所见，此项目的效果看上去并没有多少**FDL**的元素在里面（最基本的Acrylic和Reveal都无，只有图标是符合FDL的），只是单纯的Win10 Modern风格（也叫**MDL**）。效果类似的项目[Winstrap](http://winstrap.azurewebsites.net/index.html)也说自己是MDL，而不是FDL。
> 
> 不过这个项目的名字ms-design起的好，完全可以说是实现了MDL风格，而不用说是FDL。
> 
> [react-uwp](https://www.react-uwp.com/)则是真正的FDL，虽然它的Reveal并非真正的Reveal，但至少有那么个意思。

感谢大佬建议。

我本人对于设计并不擅长，初衷是想做一个实现Fluent Design的一个Vue组件库。对于组件UI，我是直接下载了Fluent Design的设计稿文件来实现的(做完了一些细微调整)。由于刚刚起步，组件比较匮乏，后期会慢慢迭代。

至于名字，是因为关于Fluent Design之类的名字都被注册了，所以换成了ms-design😂😂😂，算是误打误撞吧……

之前没有用过react-uwp Winstrap 这两个库，我会在以后的组件编写中参考它们的CSS实现。

另外我也会修改仓库描述，加入你所说的MDL（具体怎么描述尚未考虑清楚，但我仍然想保留Fluent Design，可以给一些建议吗？）

再次感谢

**Comment by UlyssesWu** [comment]
FDL基本上是从MDL进化出来的，参照react-uwp，可以一键在FDL和MDL（去掉Fluent效果）之间切换（可以对比一下效果）：

![qq 20190110115849](https://user-images.githubusercontent.com/4312781/50945388-62ce8c00-14cf-11e9-9952-d3becf6bf73a.png)

先把Acrylic（[半透明材质](https://docs.microsoft.com/zh-cn/windows/uwp/design/style/acrylic)）和Reveal（[显示焦点](https://docs.microsoft.com/zh-cn/windows/uwp/design/style/reveal-focus)）效果做出来，也就可以说自己是FDL设计了吧。随后再贴近一下FDL的[其他设计](https://docs.microsoft.com/zh-cn/windows/uwp/design/fluent-design-system/)，如响应式布局、深度、动效之类。

**Comment by ApsarasX** [comment]
> FDL基本上是从MDL进化出来的，参照react-uwp，可以一键在FDL和MDL（去掉Fluent效果）之间切换（可以对比一下效果）：
> 
> ![qq 20190110115849](https://user-images.githubusercontent.com/4312781/50945388-62ce8c00-14cf-11e9-9952-d3becf6bf73a.png)
> 
> 先把Acrylic（[半透明材质](https://docs.microsoft.com/zh-cn/windows/uwp/design/style/acrylic)）和Reveal（[显示焦点](https://docs.microsoft.com/zh-cn/windows/uwp/design/style/reveal-focus)）效果做出来，也就可以说自己是FDL设计了吧。随后再贴近一下FDL的[其他设计](https://docs.microsoft.com/zh-cn/windows/uwp/design/fluent-design-system/)，如响应式布局、深度、动效之类。

Thanks
