### ISSUE TITLE
说实话，巨硬画风略简陋，为何不参考Avdan给巨硬设计的画风

### ISSUE THREAD

**Issue by Akimotorakiyu** [ms-design/ms-design#36]
说实话，目前巨硬画风略简陋，为何不参考Avdan给巨硬设计的画风?
https://www.bilibili.com/video/av37981402?from=search&seid=17645721577102856176

**Comment by ApsarasX** [comment]
> 说实话，目前巨硬画风略简陋，为何不参考Avdan给巨硬设计的画风?
> https://www.bilibili.com/video/av37981402?from=search&seid=17645721577102856176

目前组件库视觉设计基本遵循Mirosoft Fluent Design设计规范，当前组件较为匮乏，待后期组件库较完善后会支持预设主题及自定义主题配置
